name: 'jincco-action'
description: 'Jincco Integration'
inputs:
  sourceDirectories:
    description: 'Comma separated list of source directories relative to repository root'
    required: true
    default: 'src/main/java'
  xmlReportFiles:
    description: 'Comma separated list of Jacoco XML reports relative to repository root'
    required: true
    default: 'build/reports/jacoco/test/jacocoTestReport.xml'
  ignoreDirectories:
    description: 'Comma separated list of source directories that should be ignored for incremental coverage'
    required: true
    default: 'src/test/java'
  pullRequest: 
    description: 'Pull request number'
    required: true
    default: ${{ github.event.pull_request.number }}
  serverUrl:
    description: 'Jincco server URL'
    required: true
    default: https://jinccov.com
  token: 
    description: 'Github Token to be used to access pull request'
    default: ${{ github.token }}
  tokenType: 
    description: 'Type of GitHub token. GtHub Actions has type ACCESS_CODE, whereas legacy PAT has type PAR and Modern PATs are JWT'
    default: ACCESS_CODE
  repository:
    description: 'Github repository in the format, either "repo_name" or "owner/repo_name"'
    required: true
    default: ${{ github.repository }}
  repositoryOwner:
    description: 'Github repositoryOwner'
    required: false
    default: ${{ github.event.repository_owner }}
outputs:
  pullRequestCoverage: # id of output
    description: 'Pull request coverage'
runs:
  using: 'node16'
  main: 'index.js'