name: 'jincco-action'
description: 'Jincco Integration'
inputs:
  sourceDirectories:
    description: 'Comma separated list of source directories relative to repository root'
    required: true
    default: 'src/main/java'
  classDirectories:
    description: 'Comma separated list of class directories relative to repository root'
    required: true
    default: 'build/classes/java/main'
  execFiles:
    description: 'Comma separated list of Jacoco exec files relative to repository root'
    required: true
    default: 'build/jacoco/test.exec'
  pullRequest: 
    description: 'Pull request number'
    required: true
    default: ${{ github.event.pull_request.number }}
  serverUrl:
    description: 'Jincco server URL'
    required: true
    default: https://jinccov.com
  token: 
    description: 'Github Token'
    required: true
  repository:
    description: 'Github repository in the format, either "repo_name" or "owner/repo_name"'
    required: true
    default: ${{ github.event.repository }}
  repositoryOwner:
    description: 'Github repositoryOwner'
    required: false
outputs:
  pullRequestCoverage: # id of output
    description: 'Pull request coverage'
runs:
  using: 'node16'
  main: 'index.js'